#!/bin/bash
echo "###### Server ProjectZomboid.$SERVER_NAME [STARTING]"
cd "$INSTALL_DIR" || exit 1

echo "$PORT" > /home/steam/config/port
echo "$SERVER_NAME" > /home/steam/config/server_name

./start-server.sh "$SERVER_NAME"
