#!/bin/bash
echo "###### Server DayZ.$SERVER_NAME [STARTING]"
cd "$INSTALL_DIR" || exit 1

echo "$PORT" > /home/steam/config/port
echo "$SERVER_NAME" > /home/steam/config/server_name

./DayZServer -config=serverDZ.cfg -port="$PORT" -profiles=profiles
