#!/bin/bash
echo "###### Server Ark.$SERVER_NAME [STARTING]"
cd $INSTALL_DIR
##### Server Config
echo $PORT > /home/steam/config/port
echo $PORT_RCON > /home/steam/config/port_rcon
echo $SERVER_NAME > /home/steam/config/server_name 
echo $PASSWORD > /home/steam/config/password

##### CONTENTS OF server_start.sh
export templdpath=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
export SteamAppId=376030

./ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?listen?SessionName=$SERVER_NAME?ServerPassword=$PASSWORD?ServerAdminPassword=$ADMIN_PASSWORD?Port=$PORT?QueryPort=$PORT_QUERY?RCONEnabled=True?RCONPort=$PORT_RCON -nosteamclient -game -server -log -crossplay

export LD_LIBRARY_PATH=$templdpath