#!/bin/bash
if [ -f /init/lib/server_start_lib.sh ]; then
    source /init/lib/server_start_lib.sh
else
    peon_server_starting() { echo "###### Server ${1}.$SERVER_NAME [STARTING]"; }
    peon_steam_ld_path_enter() { export templdpath=$LD_LIBRARY_PATH; export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH; }
    peon_steam_ld_path_exit() { export LD_LIBRARY_PATH=$templdpath; }
fi
source /actions/configure_settings

peon_server_starting "Palworld"
cd $INSTALL_DIR
##### Server Config
echo $PORT > /home/steam/config/port
echo $SERVER_NAME > /home/steam/config/server_name 
echo $PASSWORD > /home/steam/config/password

check_config_file
dedicated_server_name=$(resolve_dedicated_server_name)
pin_dedicated_server_name "$dedicated_server_name"
update_server_settings

##### CONTENTS OF server_start.sh
peon_steam_ld_path_enter
export SteamAppId=2394010


# NOTE: Minimum password length is 5 characters & Password cant be in the server name.
# NOTE: You need to make sure the ports are being forwarded to your server through your local router & firewall.
echo -n "STARTED" > $STATE_FILE
./PalServer.sh -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS 

peon_steam_ld_path_exit