#!/bin/bash
echo "##### Processing additional checks [V-Rising]"
if ! grep -o 'avx[^ ]*' /proc/cpuinfo; then
	unsupported_file="$INSTALL_DIR/VRisingServer_Data/Plugins/x86_64/lib_burst_generated.dll"
	echo "AVX or AVX2 not supported; Check if unsupported ${unsupported_file} exists"
	if [ -f "${s}/${unsupported_file}" ]; then
		echo "Changing ${unsupported_file} as attempt to fix issues..."
		mv "${s}/${unsupported_file}" "${s}/${unsupported_file}.bak"
	fi
fi