  docs:
    container_name: peon.docs
    hostname: peon.docs
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ${PWD}/documentation/site:/usr/share/nginx/html:ro
    networks:
      zugnet:
        ipv4_address: 172.20.0.6
    restart: unless-stopped
