#!/bin/bash
echo "###### Server DST.$SERVER_NAME [STARTING]"
cd "$INSTALL_DIR" || exit 1

echo "$PORT" > /home/steam/config/port
echo "$SERVER_NAME" > /home/steam/config/server_name

./bin64/dontstarve_dedicated_server_nullrenderer_x64 -console -cluster "$CLUSTER_NAME" -shard "$SHARD_NAME"
