#!/bin/bash
echo "###### Server ArmaReforger.$SERVER_NAME [STARTING]"
cd "$INSTALL_DIR" || exit 1

echo "$PORT" > /home/steam/config/port
echo "$PORT_A2S" > /home/steam/config/port_a2s
echo "$SERVER_NAME" > /home/steam/config/server_name

./ArmaReforgerServer -config ./config.json -profile ./profile -port "$PORT"
