#!/bin/bash
source /init/lib/server_start_lib.sh
peon_server_starting "Satisfactory"
cd $INSTALL_DIR
##### Server Config
echo $QUERYPORT > /home/steam/config/port
##### CONTENTS OF server_start.sh
peon_steam_ld_path_enter
export SteamAppId=1690800

./FactoryServer.sh -ServerQueryPort=$QUERYPORT -BeaconPort=$BEACONPORT -Port=$PORT -multihome=$IP

peon_steam_ld_path_exit