#!/bin/bash
echo "###### Server Satisfactory.$SERVER_NAME [STARTING]"
cd $INSTALL_DIR
##### Server Config
echo $QUERYPORT > /home/steam/config/port
##### CONTENTS OF server_start.sh
export templdpath=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
export SteamAppId=1690800

./FactoryServer.sh -ServerQueryPort=$QUERYPORT -BeaconPort=$BEACONPORT -Port=$PORT -multihome=$IP

export LD_LIBRARY_PATH=$templdpath