#!/bin/bash
if [ -f /init/lib/server_start_lib.sh ]; then
    source /init/lib/server_start_lib.sh
else
    peon_server_starting() { echo "###### Server ${1}.$SERVER_NAME [STARTING]"; }
    peon_steam_ld_path_enter() { export templdpath=$LD_LIBRARY_PATH; export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH; }
    peon_steam_ld_path_exit() { export LD_LIBRARY_PATH=$templdpath; }
fi
peon_server_starting "Satisfactory"
cd $INSTALL_DIR
##### Server Config
echo $QUERYPORT > /home/steam/config/port
##### CONTENTS OF server_start.sh
peon_steam_ld_path_enter
export SteamAppId=1690800

./FactoryServer.sh -ServerQueryPort=$QUERYPORT -BeaconPort=$BEACONPORT -Port=$PORT -multihome=$IP

peon_steam_ld_path_exit