#!/bin/bash
source /init/lib/server_start_lib.sh
peon_server_starting "Valheim"
cd $INSTALL_DIR
##### Server Config
echo $PORT > /home/steam/config/port
echo $SERVER_NAME > /home/steam/config/server_name 
echo $WORLD_NAME > /home/steam/config/world_name
echo $PASSWORD > /home/steam/config/password

##### CONTENTS OF server_start.sh
peon_steam_ld_path_enter
export SteamAppId=892970

# Tip: Make a local copy of this script to avoid it being overwritten by steam.
# NOTE: Minimum password length is 5 characters & Password cant be in the server name.
# NOTE: You need to make sure the ports 2456-2458 is being forwarded to your server through your local router & firewall.
./valheim_server.x86_64 -name $SERVER_NAME -port $PORT -world $WORLD_NAME -password $PASSWORD -public 1

peon_steam_ld_path_exit