#!/bin/bash
echo "###### Server L4D2.$SERVER_NAME [STARTING]"
cd "$INSTALL_DIR" || exit 1

echo "$PORT" > /home/steam/config/port
echo "$SERVER_NAME" > /home/steam/config/server_name

./srcds_run -game left4dead2 -console +map "$MAP" +maxplayers "$MAXPLAYERS" -port "$PORT"
