#!/bin/bash
echo "###### Server Factorio.$SERVER_NAME [STARTING]"
cd "$INSTALL_DIR" || exit 1

echo "$PORT" > /home/steam/config/port
echo "$RCON_PORT" > /home/steam/config/port_rcon
echo "$SERVER_NAME" > /home/steam/config/server_name

./bin/x64/factorio --start-server-load-latest --server-settings /home/steam/config/server-settings.json --port "$PORT"
