#!/bin/bash
echo "###### Server ETS2.$SERVER_NAME [STARTING]"
cd "$INSTALL_DIR" || exit 1

echo "$PORT" > /home/steam/config/port
echo "$SERVER_NAME" > /home/steam/config/server_name

./bin/linux_x64/eurotrucks2_server +server_cfg server_config.sii
