#!/bin/bash
echo "###### Server Terraria.$SERVER_NAME [STARTING]"
cd "$INSTALL_DIR" || exit 1

echo "$PORT" > /home/steam/config/port
echo "$SERVER_NAME" > /home/steam/config/server_name
echo "$PASSWORD" > /home/steam/config/password

./TerrariaServer.bin.x86_64 -config serverconfig.txt -port "$PORT"
