#!/bin/bash
echo "###### Server Squad.$SERVER_NAME [STARTING]"
cd "$INSTALL_DIR" || exit 1

echo "$PORT" > /home/steam/config/port
echo "$QUERYPORT" > /home/steam/config/query_port
echo "$RCON_PORT" > /home/steam/config/port_rcon
echo "$SERVER_NAME" > /home/steam/config/server_name

./SquadGameServer.sh Port="$PORT" QueryPort="$QUERYPORT" FIXEDMAXPLAYERS="$MAXPLAYERS"
