#!/bin/bash
echo "###### Server Rust.$SERVER_NAME [STARTING]"
cd "$INSTALL_DIR" || exit 1

echo "$PORT" > /home/steam/config/port
echo "$RCON_PORT" > /home/steam/config/port_rcon
echo "$SERVER_NAME" > /home/steam/config/server_name

./RustDedicated -batchmode +server.port "$PORT" +server.hostname "$SERVER_NAME" +server.identity default +server.level "$WORLD_NAME" +server.worldsize "$WORLD_SIZE" +server.maxplayers "$MAXPLAYERS"
